GET http://localhost:3000/todo HTTP/1.1

###
GET http://localhost:3000/todo/jsdf HTTP/1.1

###
POST http://localhost:3000/todo HTTP/1.1
Content-Type: application/json

{
    "title": "Get a phone",
    "description": "purchase with cash"
}
###
PUT http://localhost:3000/todo/dsaa HTTP/1.1
Content-Type: application/json

{
    "title": "Get a phone",
    "description": "purchase with cash"
}

###
DELETE http://localhost:3000/todo/jsdf HTTP/1.1